{
  description = "Dash0 Nix User Repository";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    {
      nixpkgs,
      flake-utils,
      ...
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        # pkgs/dash0/default.nix is generated by GoReleaser on each dash0-cli
        # release; a placeholder is committed so the flake is buildable before
        # the first release.
        dash0 = pkgs.callPackage ./pkgs/dash0/default.nix { };
      in
      {
        packages = {
          inherit dash0;
          default = dash0;
        };
      }
    );
}
