# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "08vny72d33v9iah0ym5idqjjampwf386hirfy3vx2p23sgf29j80";
    armv6l-linux = "0m60208ks255bhrrarrnik8l493jg0hhrma1w41v9axzhnh69i3i";
    aarch64-linux = "0v2s17v54msirl17i2sgskp4x9v5zm8spfykqazww5zwxzqkiyb0";
    x86_64-darwin = "13bxajjwkqy3jdgl3gdxlpad4r2pskcf3krm0xa07j287mn52yq1";
    aarch64-darwin = "15lb3i1c7xxdvid3qakx70k9z70h3c7bpqlvp98h1ljmpai8ggs8";
  };

  urlMap = {
    x86_64-linux = "https://github.com/dash0hq/dash0-cli/releases/download/v1.16.1/dash0_1.16.1_linux_amd64.tar.gz";
    armv6l-linux = "https://github.com/dash0hq/dash0-cli/releases/download/v1.16.1/dash0_1.16.1_linux_arm.tar.gz";
    aarch64-linux = "https://github.com/dash0hq/dash0-cli/releases/download/v1.16.1/dash0_1.16.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/dash0hq/dash0-cli/releases/download/v1.16.1/dash0_1.16.1_macos_amd64.tar.gz";
    aarch64-darwin = "https://github.com/dash0hq/dash0-cli/releases/download/v1.16.1/dash0_1.16.1_macos_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dash0";
  version = "1.16.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./dash0 $out/bin/dash0
    installShellCompletion ./completions/*
  '';

  meta = {
    description = "CLI to interact with Dash0";
    homepage = "https://github.com/dash0hq/dash0-cli";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
