# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0l5zc508vz7wxki0i68kgd7afxd1insf3fdk91wh0g7jrwyim99v";
    armv6l-linux = "1cqf6nck6i5d5wmx0vddx8za0cgvf940iclgx9m6mgwghflamz0x";
    aarch64-linux = "0vqzwzggv520vpn9aiyd9lsal708j4vhba5fvqjix8gpizz8gial";
    x86_64-darwin = "0n7q91lq6g1nb1zy4qcbqnb0m559wl3mp5inva28gjbymh228gx1";
    aarch64-darwin = "1k26spw9w9b7h0my80n20rnx457jlx26xazggq7kl0ck17s9vm9p";
  };

  urlMap = {
    x86_64-linux = "https://github.com/dash0hq/dash0-cli/releases/download/v1.15.4/dash0_1.15.4_linux_amd64.tar.gz";
    armv6l-linux = "https://github.com/dash0hq/dash0-cli/releases/download/v1.15.4/dash0_1.15.4_linux_arm.tar.gz";
    aarch64-linux = "https://github.com/dash0hq/dash0-cli/releases/download/v1.15.4/dash0_1.15.4_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/dash0hq/dash0-cli/releases/download/v1.15.4/dash0_1.15.4_macos_amd64.tar.gz";
    aarch64-darwin = "https://github.com/dash0hq/dash0-cli/releases/download/v1.15.4/dash0_1.15.4_macos_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dash0";
  version = "1.15.4";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./dash0 $out/bin/dash0
    installShellCompletion ./completions/*
  '';

  meta = {
    description = "CLI to interact with Dash0";
    homepage = "https://github.com/dash0hq/dash0-cli";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
