# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0ysmymjbjsjyfgwb8y6zlyxnjspxfqgv064y1cxbidr3pidkv963";
    armv6l-linux = "1fdr78svgz9ygqd56fp6i32gyiv6zkz8gzym4xvxa27swmqn8grg";
    aarch64-linux = "13910ybg17rzq2k3f91lz7bdxhq7ibssyy03sa0gq13rkd72n6jv";
    x86_64-darwin = "0ak8d5nmkb3wpg4j9602d229akpp6rws6ihx3kp60ijz285f4dy2";
    aarch64-darwin = "0lz8r90vnbbc6xj360b13mk5nz1rfjwwqljzw3b2sa9ab516rn7f";
  };

  urlMap = {
    x86_64-linux = "https://github.com/dash0hq/dash0-cli/releases/download/v1.15.3/dash0_1.15.3_linux_amd64.tar.gz";
    armv6l-linux = "https://github.com/dash0hq/dash0-cli/releases/download/v1.15.3/dash0_1.15.3_linux_arm.tar.gz";
    aarch64-linux = "https://github.com/dash0hq/dash0-cli/releases/download/v1.15.3/dash0_1.15.3_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/dash0hq/dash0-cli/releases/download/v1.15.3/dash0_1.15.3_macos_amd64.tar.gz";
    aarch64-darwin = "https://github.com/dash0hq/dash0-cli/releases/download/v1.15.3/dash0_1.15.3_macos_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dash0";
  version = "1.15.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./dash0 $out/bin/dash0
    installShellCompletion ./completions/*
  '';

  meta = {
    description = "CLI to interact with Dash0";
    homepage = "https://github.com/dash0hq/dash0-cli";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
